# .github/workflows/java-ci.yaml
name: Java CI

run-name: ${{ github.workflow }} - ${{ github.event_name }} by @${{ github.actor 

on:
  pull_request:
  push:
    paths:
      - Backend/**

jobs:
  maven-verify:
    name: Maven Verify
    timeout-minutes: 5
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend/TravelExpensePro

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven Verify
        run: mvn -B verify --file pom.xml
