name: Storybook Tests yarn
run-name: ${{ github.event_name }} • ${{ github.event.head_commit.message }}
on:
  push:
    paths:
      - Frontend/travel-expense-pro/**
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/travel-expense-pro
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache-yarn
        uses: actions/cache@v4
        with:
          path: |
            Frontend/travel-expense-pro/pnpm-lock.yaml
            Frontend/travel-expense-pro/node_modules
          key: ${{ hashFiles('Frontend/travel-expense-pro/package-lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: npx playwright --version

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
