name: Storybook Tests yarn
run-name: ${{ github.event_name }} • ${{ github.event.head_commit.message }}
on:
  push:
    paths:
      - Frontend/travel-expense-pro/**
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/travel-expense-pro
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Cache yarn.lock
        id: cache-yarn
        uses: actions/cache@v4
        with:
          path: Frontend/travel-expense-pro/yarn.lock
          key: ${{ hashFiles('Frontend/travel-expense-pro/package-lock.json') }}

      - name: Use Node.js 22 without caching
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Use Node.js 22 with caching
        if: steps.cache-yarn.outputs.cache-hit == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: Frontend/travel-expense-pro/yarn.lock

      - name: Install dependencies
        run: yarn install

      - id: playwright-version
        run: echo "result=$(npx playwright --version)" >> $GITHUB_OUTPUT
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ steps.playwright-version.outputs.result }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
