name: Storybook Tests
run-name: ${{ github.event_name }} • ${{ github.event.head_commit.message }}
on: push
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/travel-expense-pro
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Cache yarn.lock
        id: cache-yarn
        uses: actions/cache@v4
        with:
          path: Frontend/travel-expense-pro/yarn.lock
          key: ${{ hashFiles('Frontend/travel-expense-pro/package-lock.json') }}
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ${{ steps.cache-yarn.outputs.cache-hit == 'true' && 'yarn' || '' }}
          cache-dependency-path: Frontend/travel-expense-pro/yarn.lock
      - name: Install dependencies
        run: yarn install
      - name: Get Playwright version
        id: get-playwright-version
        run : echo "PLAYWRIGHT_VERSION=$(npx playwright --version)" >> "$GITHUB_OUTPUT"
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ steps.get-playwright-version.outputs.PLAYWRIGHT_VERSION }}
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
